import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/footer";
import Navbar from "@/components/navigation/navbar";
import ModalProvider from "@/providers/modal-provider";
import { Toaster } from "@/components/ui/sonner";

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ModalProvider />
        <Toaster duration={1500} position="top-center" />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
